# Generated by Django 4.2.13 on 2026-08-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الهيكل')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='رقم اللوحة')),
                ('brand', models.CharField(max_length=100, verbose_name='ماركة المركبة')),
                ('manufacture_year', models.PositiveIntegerField(verbose_name='سنة الصنع')),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم التسلسلي')),
                ('registration_expiry', models.DateField(verbose_name='تاريخ انتهاء الاستمارة')),
                ('inspection_expiry', models.DateField(verbose_name='تاريخ انتهاء الفحص الدوري')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'باص',
                'verbose_name_plural': 'الباصات',
                'ordering': ['-created_at'],
            },
        ),
    ]
