# Generated by Django 4.2.13 on 2026-08-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name_ar', models.CharField(default='مركز رؤية للتأهيل', max_length=200, verbose_name='اسم المركز (عربي)')),
                ('center_name_en', models.CharField(blank=True, default='Roya Rehabilitation Center', max_length=200, verbose_name='اسم المركز (إنجليزي)')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم التواصل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='الموقع الإلكتروني')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='الشعار')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات المركز',
                'verbose_name_plural': 'إعدادات المركز',
            },
        ),
    ]
