# Generated by Django 4.2.13 on 2026-09-01 20:16

from django.db import migrations, models


def _set_default_weekly_off_days(apps, schema_editor):
    """يضبط الافتراض المقترح (الجمعة+السبت) على صف الإعدادات الوحيد إن وُجد بالفعل."""
    SiteSettings = apps.get_model('core', 'SiteSettings')
    SiteSettings.objects.filter(pk=1).update(weekly_off_days=['friday', 'saturday'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفصل الدراسي')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فصل دراسي',
                'verbose_name_plural': 'الفصول الدراسية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المناسبة/العطلة')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عطلة رسمية',
                'verbose_name_plural': 'العطل الرسمية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weekly_off_days',
            field=models.JSONField(blank=True, default=list, verbose_name='أيام الإجازة الأسبوعية'),
        ),
        migrations.RunPython(_set_default_weekly_off_days, migrations.RunPython.noop),
    ]
