# Generated by Django 4.2.13 on 2026-09-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_academicterm_holiday_sitesettings_weekly_off_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'صباحي'), ('evening', 'مسائي')], max_length=10, verbose_name='الفترة')),
                ('driver_name', models.CharField(blank=True, max_length=150, verbose_name='اسم السائق')),
                ('supervisor_name', models.CharField(blank=True, max_length=150, verbose_name='اسم المشرف/ة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.bus', verbose_name='الباص')),
            ],
            options={
                'verbose_name': 'فترة تشغيل الباص',
                'verbose_name_plural': 'فترات تشغيل الباصات',
                'ordering': ['bus', 'shift'],
                'unique_together': {('bus', 'shift')},
            },
        ),
    ]
