# Generated by Django 4.2.13 on 2026-09-16 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_busshift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busshift',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='busshift',
            name='supervisor_name',
        ),
        migrations.AddField(
            model_name='busshift',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_bus_shifts', to=settings.AUTH_USER_MODEL, verbose_name='السائق'),
        ),
        migrations.AddField(
            model_name='busshift',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'bus_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_bus_shifts', to=settings.AUTH_USER_MODEL, verbose_name='المشرف/ة'),
        ),
    ]
