from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from apps.students.models import Student, Guardian, FamilyInfo
import random
from datetime import date, timedelta

User = get_user_model()

STUDENTS = [
    {
        'first_name': 'محمد', 'middle_name': 'عبدالله', 'grandfather_name': '', 'family_name': 'الغامدي',
        'national_id': '1056789012',
        'date_of_birth': '2015-03-12',
        'gender': 'male',
        'nationality': 'سعودي',
        'disability_type': 'autism',
        'disability_degree': 'moderate',
        'diagnosis': 'اضطراب طيف التوحد - الدرجة الثانية',
        'educational_level': 'elementary',
        'school_name': 'مدرسة التربية الفكرية بالرياض',
        'grade': 'الثاني الابتدائي',
        'referral_source': 'hospital',
        'referral_source_detail': 'مستشفى الملك فهد التخصصي',
        'status': 'active',
        'registration_date': '2026-01-15',
        'notes': 'يحتاج جلسات نطق وتخاطب أسبوعية',
        'guardian': {
            'full_name': 'عبدالله سعد الغامدي',
            'relationship': 'father',
            'national_id': '1023456789',
            'phone': '0501234567',
            'phone_alt': '0551234567',
            'email': 'a.ghamdi@email.com',
            'address': 'الرياض - حي العليا - شارع العروبة',
            'is_primary_contact': True,
        },
        'family': {
            'family_size': 6,
            'sibling_order': 2,
            'parents_status': 'married',
            'income_range': 'medium',
            'monthly_income': 8500,
            'housing_type': 'owned',
            'social_notes': 'أسرة متعاونة وملتزمة بالحضور',
        },
    },
    {
        'first_name': 'نورة', 'middle_name': 'خالد', 'grandfather_name': '', 'family_name': 'القحطاني',
        'national_id': '1067890123',
        'date_of_birth': '2017-07-22',
        'gender': 'female',
        'nationality': 'سعودية',
        'disability_type': 'down',
        'disability_degree': 'mild',
        'diagnosis': 'متلازمة داون - بسيطة إلى متوسطة',
        'educational_level': 'kindergarten',
        'school_name': 'روضة المستقبل',
        'grade': 'KG2',
        'referral_source': 'school',
        'referral_source_detail': 'روضة الأطفال الوطنية',
        'status': 'active',
        'registration_date': '2026-02-01',
        'guardian': {
            'full_name': 'منى إبراهيم السالم',
            'relationship': 'mother',
            'national_id': '2034567890',
            'phone': '0559876543',
            'email': 'mona.s@email.com',
            'address': 'الرياض - حي الروضة',
            'is_primary_contact': True,
        },
        'family': {
            'family_size': 4,
            'sibling_order': 1,
            'parents_status': 'married',
            'income_range': 'high',
            'monthly_income': 15000,
            'housing_type': 'owned',
            'social_notes': 'الأم متفرغة لرعاية الطفلة',
        },
    },
    {
        'first_name': 'يوسف', 'middle_name': 'أحمد', 'grandfather_name': '', 'family_name': 'العتيبي',
        'national_id': '1078901234',
        'date_of_birth': '2013-11-05',
        'gender': 'male',
        'nationality': 'سعودي',
        'disability_type': 'intellectual',
        'disability_degree': 'moderate',
        'diagnosis': 'إعاقة ذهنية متوسطة',
        'educational_level': 'special',
        'school_name': 'مركز تعليم ذوي الاحتياجات',
        'grade': 'المستوى الثالث',
        'referral_source': 'ministry',
        'referral_source_detail': 'وزارة التعليم - برنامج التربية الخاصة',
        'status': 'active',
        'registration_date': '2025-09-10',
        'guardian': {
            'full_name': 'أحمد محمد العتيبي',
            'relationship': 'father',
            'national_id': '1045678901',
            'phone': '0503456789',
            'address': 'جدة - حي الصفا',
            'is_primary_contact': True,
        },
        'family': {
            'family_size': 7,
            'sibling_order': 3,
            'parents_status': 'married',
            'income_range': 'low',
            'monthly_income': 4500,
            'housing_type': 'rented',
            'other_special_needs': True,
            'social_notes': 'الأسرة تعيل طفلاً آخر بإعاقة سمعية',
        },
    },
    {
        'first_name': 'ريم', 'middle_name': 'فهد', 'grandfather_name': '', 'family_name': 'الشهري',
        'national_id': '2089012345',
        'date_of_birth': '2016-05-18',
        'gender': 'female',
        'nationality': 'سعودية',
        'disability_type': 'speech',
        'disability_degree': 'mild',
        'diagnosis': 'تأخر في اكتساب اللغة وعسر الكلام',
        'educational_level': 'kindergarten',
        'school_name': 'روضة الوردة',
        'referral_source': 'specialist',
        'referral_source_detail': 'دكتور عادل الحربي - استشاري أطفال',
        'status': 'active',
        'registration_date': '2026-03-05',
        'guardian': {
            'full_name': 'فهد سلطان الشهري',
            'relationship': 'father',
            'national_id': '1056781234',
            'phone': '0505678901',
            'phone_alt': '0125678901',
            'address': 'الدمام - حي الشاطئ',
            'is_primary_contact': True,
        },
        'family': {
            'family_size': 5,
            'sibling_order': 2,
            'parents_status': 'married',
            'income_range': 'medium',
            'monthly_income': 9000,
            'housing_type': 'owned',
        },
    },
    {
        'first_name': 'عمر', 'middle_name': 'سالم', 'grandfather_name': '', 'family_name': 'الدوسري',
        'national_id': '1090123456',
        'date_of_birth': '2012-08-30',
        'gender': 'male',
        'nationality': 'سعودي',
        'disability_type': 'physical',
        'disability_degree': 'moderate',
        'diagnosis': 'شلل دماغي - نوع التشنج',
        'educational_level': 'elementary',
        'school_name': 'مدرسة الأمل للتربية الخاصة',
        'grade': 'الرابع الابتدائي',
        'referral_source': 'hospital',
        'referral_source_detail': 'مستشفى الاطفال بالرياض',
        'status': 'active',
        'registration_date': '2025-11-20',
        'guardian': {
            'full_name': 'سالم عمر الدوسري',
            'relationship': 'father',
            'national_id': '1012345609',
            'phone': '0567890123',
            'address': 'الرياض - حي النزهة',
            'is_primary_contact': True,
        },
        'family': {
            'family_size': 8,
            'sibling_order': 5,
            'parents_status': 'married',
            'income_range': 'very_low',
            'monthly_income': 2800,
            'housing_type': 'rented',
            'social_notes': 'الأسرة بحاجة لدعم اجتماعي',
        },
    },
    {
        'first_name': 'لمى', 'middle_name': 'عبدالرحمن', 'grandfather_name': '', 'family_name': 'الحربي',
        'national_id': '2001234567',
        'date_of_birth': '2018-02-14',
        'gender': 'female',
        'nationality': 'سعودية',
        'disability_type': 'autism',
        'disability_degree': 'severe',
        'diagnosis': 'اضطراب طيف التوحد - الدرجة الثالثة مع تأخر لغوي',
        'educational_level': 'none',
        'referral_source': 'family',
        'status': 'pending',
        'registration_date': '2026-04-20',
        'guardian': {
            'full_name': 'هيفاء محمد الحربي',
            'relationship': 'mother',
            'phone': '0545678901',
            'address': 'مكة المكرمة - حي العزيزية',
            'is_primary_contact': True,
        },
        'family': {
            'family_size': 3,
            'sibling_order': 1,
            'parents_status': 'divorced',
            'income_range': 'very_low',
            'monthly_income': 2000,
            'housing_type': 'relative',
            'social_notes': 'الأم مطلقة وتعتمد على أهلها',
        },
    },
    {
        'first_name': 'تركي', 'middle_name': 'ناصر', 'grandfather_name': '', 'family_name': 'الزهراني',
        'national_id': '1102345678',
        'date_of_birth': '2010-12-01',
        'gender': 'male',
        'nationality': 'سعودي',
        'disability_type': 'hearing',
        'disability_degree': 'severe',
        'diagnosis': 'فقدان سمعي حسي عصبي ثنائي',
        'educational_level': 'intermediate',
        'school_name': 'مدرسة الصم وضعاف السمع',
        'grade': 'الأول المتوسط',
        'referral_source': 'ngo',
        'referral_source_detail': 'جمعية الصم وضعاف السمع',
        'status': 'active',
        'registration_date': '2025-08-15',
        'guardian': {
            'full_name': 'ناصر علي الزهراني',
            'relationship': 'father',
            'national_id': '1089012345',
            'phone': '0523456789',
            'email': 'nasser.z@email.com',
            'address': 'الطائف - حي الشفا',
            'is_primary_contact': True,
        },
        'family': {
            'family_size': 5,
            'sibling_order': 1,
            'parents_status': 'married',
            'income_range': 'medium',
            'monthly_income': 7200,
            'housing_type': 'owned',
        },
    },
    {
        'first_name': 'دانة', 'middle_name': 'خالد', 'grandfather_name': '', 'family_name': 'المالكي',
        'national_id': '2013456789',
        'date_of_birth': '2019-09-08',
        'gender': 'female',
        'nationality': 'سعودية',
        'disability_type': 'learning',
        'disability_degree': 'mild',
        'diagnosis': 'صعوبات تعلم - عسر القراءة',
        'educational_level': 'elementary',
        'school_name': 'مدرسة الرواد الابتدائية',
        'grade': 'الأول الابتدائي',
        'referral_source': 'school',
        'referral_source_detail': 'معلمة الصف الأول',
        'status': 'active',
        'registration_date': '2026-01-28',
        'guardian': {
            'full_name': 'خالد عبدالله المالكي',
            'relationship': 'father',
            'phone': '0534567890',
            'address': 'الرياض - حي الملقا',
            'is_primary_contact': True,
        },
        'family': {
            'family_size': 6,
            'sibling_order': 3,
            'parents_status': 'married',
            'income_range': 'high',
            'monthly_income': 18000,
            'housing_type': 'owned',
        },
    },
    {
        'first_name': 'فيصل', 'middle_name': 'محمد', 'grandfather_name': '', 'family_name': 'السبيعي',
        'national_id': '1123456780',
        'date_of_birth': '2011-04-25',
        'gender': 'male',
        'nationality': 'سعودي',
        'disability_type': 'multiple',
        'disability_degree': 'severe',
        'diagnosis': 'إعاقة مركبة: ذهنية + حركية',
        'educational_level': 'special',
        'school_name': 'مركز رعاية ذوي الاحتياجات',
        'referral_source': 'hospital',
        'status': 'inactive',
        'registration_date': '2024-06-10',
        'notes': 'أوقف الخدمة مؤقتاً بسبب سفر الأسرة',
        'guardian': {
            'full_name': 'محمد فيصل السبيعي',
            'relationship': 'father',
            'phone': '0512345678',
            'address': 'أبها - حي الموظفين',
            'is_primary_contact': True,
        },
        'family': {
            'family_size': 9,
            'sibling_order': 7,
            'parents_status': 'married',
            'income_range': 'low',
            'monthly_income': 5000,
            'housing_type': 'government',
        },
    },
    {
        'first_name': 'سارة', 'middle_name': 'علي', 'grandfather_name': '', 'family_name': 'الغامدي',
        'national_id': '2024567891',
        'date_of_birth': '2014-06-19',
        'gender': 'female',
        'nationality': 'سعودية',
        'disability_type': 'behavioral',
        'disability_degree': 'moderate',
        'diagnosis': 'اضطراب نقص الانتباه وفرط الحركة (ADHD)',
        'educational_level': 'elementary',
        'school_name': 'مدرسة نجمة الشمال',
        'grade': 'الثالث الابتدائي',
        'referral_source': 'school',
        'referral_source_detail': 'المرشدة الطلابية',
        'status': 'active',
        'registration_date': '2026-02-14',
        'guardian': {
            'full_name': 'نوف حسن الغامدي',
            'relationship': 'mother',
            'phone': '0576543210',
            'email': 'noof.g@email.com',
            'address': 'الرياض - حي اليرموك',
            'is_primary_contact': True,
        },
        'family': {
            'family_size': 5,
            'sibling_order': 2,
            'parents_status': 'divorced',
            'income_range': 'low',
            'monthly_income': 3500,
            'housing_type': 'rented',
            'social_notes': 'الأم تعمل وتعيل الأسرة بمفردها',
        },
    },
]


class Command(BaseCommand):
    help = 'Seed demo student data'

    def handle(self, *args, **options):
        if Student.objects.count() >= 5:
            print('[SKIP] Demo data already exists.')
            return

        admin = User.objects.filter(role='admin').first()

        for i, data in enumerate(STUDENTS):
            guardian_data = data.pop('guardian')
            family_data   = data.pop('family')

            student = Student.objects.create(created_by=admin, **data)

            Guardian.objects.create(student=student, **guardian_data)

            FamilyInfo.objects.create(student=student, **family_data)

            print(f'[{i+1:02d}] Created student #{student.pk} - File: {student.file_number}')

        print(f'Done. Total students: {Student.objects.count()}')
