# Generated by Django 4.2.13 on 2026-08-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_assigned_branch_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodulepermission',
            name='module',
            field=models.CharField(choices=[('students', 'ملفات الطلاب'), ('medical_file', 'الملف الطبي'), ('reports', 'التقارير'), ('audit_logs', 'سجل العمليات'), ('users', 'المستخدمون'), ('settings', 'الإعدادات')], max_length=20, verbose_name='الوحدة'),
        ),
    ]
