# Generated by Django 4.2.13 on 2026-08-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usermodulepermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodulepermission',
            name='module',
            field=models.CharField(choices=[('students', 'ملفات الطلاب'), ('medical_file', 'الملف الطبي'), ('assessments', 'المقاييس والخطط الدراسية'), ('reports', 'التقارير'), ('audit_logs', 'سجل العمليات'), ('users', 'المستخدمون'), ('settings', 'الإعدادات')], max_length=20, verbose_name='الوحدة'),
        ),
    ]
