# Generated by Django 4.2.13 on 2026-09-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usermodulepermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('manager', 'مدير'), ('specialist', 'أخصائي'), ('reception', 'استقبال'), ('viewer', 'مشاهد'), ('driver', 'سائق'), ('bus_supervisor', 'مشرف/ة الباص')], default='viewer', max_length=20, verbose_name='الدور الوظيفي'),
        ),
    ]
