# Generated by Django 4.2.13 on 2026-09-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodulepermission',
            name='module',
            field=models.CharField(choices=[('students', 'ملفات الطلاب'), ('medical_file', 'الملف الطبي'), ('assessments', 'المقاييس والخطط الدراسية'), ('reports', 'التقارير'), ('attendance', 'الحضور والغياب'), ('schedule', 'الجدول الدراسي'), ('buses', 'الباصات')], max_length=20, verbose_name='الوحدة'),
        ),
    ]
