# Generated by Django 4.2.13 on 2026-08-31 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0016_dailymedicalcheckin_blood_pressure_diastolic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم المقياس')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'مقياس',
                'verbose_name_plural': 'المقاييس',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentScaleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pre', 'قبلي'), ('post', 'بعدي')], max_length=4, verbose_name='النوع')),
                ('label', models.CharField(max_length=100, verbose_name='التسمية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_options', to='assessments.assessment', verbose_name='المقياس')),
            ],
            options={
                'verbose_name': 'خيار تقدير',
                'verbose_name_plural': 'خيارات التقدير',
                'ordering': ['kind', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(verbose_name='تاريخ البدء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات عامة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assessments', to='assessments.assessment', verbose_name='المقياس')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_assessments', to=settings.AUTH_USER_MODEL, verbose_name='بدأه')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.student', verbose_name='المستفيد')),
            ],
            options={
                'verbose_name': 'تقييم طالب',
                'verbose_name_plural': 'تقييمات الطلاب',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القسم')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.assessment', verbose_name='المقياس')),
            ],
            options={
                'verbose_name': 'قسم المقياس',
                'verbose_name_plural': 'أقسام المقياس',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص المهارة/السؤال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment', verbose_name='المقياس')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='assessments.assessmentsection', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'سؤال المقياس',
                'verbose_name_plural': 'أسئلة المقياس',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_text', models.TextField(blank=True, verbose_name='خطة التطبيق')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_answers', to='assessments.assessmentscaleoption', verbose_name='التقدير البعدي')),
                ('pre_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_answers', to='assessments.assessmentscaleoption', verbose_name='التقدير القبلي')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='assessments.assessmentquestion', verbose_name='السؤال')),
                ('student_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.studentassessment', verbose_name='التقييم')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
                'unique_together': {('student_assessment', 'question')},
            },
        ),
    ]
