# Generated by Django 4.2.13 on 2026-05-02 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='رقم الملف')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية / الإقامة')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('nationality', models.CharField(max_length=100, verbose_name='الجنسية')),
                ('status', models.CharField(choices=[('pending', 'في انتظار القبول'), ('active', 'نشط'), ('inactive', 'غير نشط'), ('graduated', 'خرّيج'), ('suspended', 'موقوف'), ('transferred', 'محوّل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/%Y/%m/', verbose_name='صورة الطالب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('national_id', 'صورة الهوية'), ('birth_certificate', 'شهادة الميلاد'), ('medical_report', 'تقرير طبي'), ('psychological_report', 'تقرير نفسي'), ('disability_card', 'بطاقة إعاقة'), ('other', 'أخرى')], max_length=30, verbose_name='نوع المرفق')),
                ('file', models.FileField(upload_to='students/attachments/%Y/%m/', verbose_name='الملف')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='students.student', verbose_name='الطالب')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رُفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='اسم ولي الأمر')),
                ('relationship', models.CharField(choices=[('father', 'أب'), ('mother', 'أم'), ('brother', 'أخ'), ('sister', 'أخت'), ('grandfather', 'جد'), ('grandmother', 'جدة'), ('uncle', 'عم / خال'), ('aunt', 'عمة / خالة'), ('other', 'أخرى')], max_length=20, verbose_name='صلة القرابة')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='رقم الهوية')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('phone_alt', models.CharField(blank=True, max_length=20, verbose_name='رقم جوال إضافي')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('is_primary_contact', models.BooleanField(default=False, verbose_name='جهة التواصل الرئيسية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'ولي أمر',
                'verbose_name_plural': 'أولياء الأمور',
            },
        ),
        migrations.CreateModel(
            name='FamilyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_size', models.PositiveIntegerField(verbose_name='عدد أفراد الأسرة')),
                ('sibling_order', models.PositiveIntegerField(verbose_name='ترتيب الطالب بين الإخوة')),
                ('parents_status', models.CharField(choices=[('married', 'متزوجان'), ('divorced', 'مطلقان'), ('father_deceased', 'الأب متوفى'), ('mother_deceased', 'الأم متوفاة'), ('both_deceased', 'كلاهما متوفى'), ('separated', 'منفصلان')], max_length=20, verbose_name='حالة الوالدين')),
                ('income_range', models.CharField(blank=True, choices=[('very_low', 'أقل من 3,000 ريال'), ('low', '3,000 – 6,000 ريال'), ('medium', '6,000 – 10,000 ريال'), ('high', '10,000 – 20,000 ريال'), ('very_high', 'أكثر من 20,000 ريال')], max_length=20, verbose_name='دخل الأسرة التقريبي')),
                ('housing_type', models.CharField(blank=True, choices=[('owned', 'ملك'), ('rented', 'إيجار'), ('relative', 'مع الأقارب'), ('government', 'سكن حكومي'), ('other', 'أخرى')], max_length=20, verbose_name='نوع السكن')),
                ('social_notes', models.TextField(blank=True, verbose_name='ملاحظات اجتماعية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_info', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'معلومات الأسرة',
                'verbose_name_plural': 'معلومات الأسر',
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['file_number'], name='students_st_file_nu_9117b6_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['national_id'], name='students_st_nationa_fc49ba_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_st_status_5e2210_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='students_st_full_na_6ea9f7_idx'),
        ),
    ]
