# Generated by Django 4.2.13 on 2026-05-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyinfo',
            options={'verbose_name': 'دراسة الحالة الاجتماعية', 'verbose_name_plural': 'دراسات الحالة الاجتماعية'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'verbose_name': 'مستفيد', 'verbose_name_plural': 'المستفيدون'},
        ),
        migrations.AddField(
            model_name='familyinfo',
            name='monthly_income',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الدخل الشهري (بالرقم)'),
        ),
        migrations.AddField(
            model_name='familyinfo',
            name='other_special_needs',
            field=models.BooleanField(default=False, verbose_name='يوجد أفراد آخرون بحاجات خاصة في الأسرة'),
        ),
        migrations.AddField(
            model_name='student',
            name='diagnosis',
            field=models.TextField(blank=True, verbose_name='التشخيص التفصيلي'),
        ),
        migrations.AddField(
            model_name='student',
            name='disability_degree',
            field=models.CharField(blank=True, choices=[('mild', 'بسيطة'), ('moderate', 'متوسطة'), ('severe', 'شديدة'), ('profound', 'شديدة جداً')], max_length=20, verbose_name='درجة الإعاقة'),
        ),
        migrations.AddField(
            model_name='student',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('intellectual', 'إعاقة ذهنية'), ('autism', 'طيف التوحد'), ('down', 'متلازمة داون'), ('physical', 'إعاقة حركية'), ('hearing', 'إعاقة سمعية'), ('visual', 'إعاقة بصرية'), ('speech', 'إعاقة لغوية / نطقية'), ('learning', 'صعوبات تعلم'), ('behavioral', 'اضطراب سلوكي'), ('multiple', 'إعاقة مركّبة'), ('other', 'أخرى')], max_length=30, verbose_name='نوع الإعاقة'),
        ),
        migrations.AddField(
            model_name='student',
            name='educational_level',
            field=models.CharField(blank=True, choices=[('none', 'لا يتعلم'), ('kindergarten', 'رياض أطفال'), ('elementary', 'ابتدائي'), ('intermediate', 'متوسط'), ('secondary', 'ثانوي'), ('university', 'جامعي'), ('special', 'برنامج تربية خاصة')], max_length=20, verbose_name='المستوى التعليمي'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='الصف / المرحلة'),
        ),
        migrations.AddField(
            model_name='student',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('hospital', 'مستشفى / عيادة'), ('school', 'مدرسة'), ('family', 'الأسرة مباشرة'), ('ngo', 'جمعية / مؤسسة'), ('ministry', 'وزارة / جهة حكومية'), ('specialist', 'طبيب / معالج'), ('other', 'أخرى')], max_length=20, verbose_name='جهة الإحالة'),
        ),
        migrations.AddField(
            model_name='student',
            name='referral_source_detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='تفاصيل جهة الإحالة'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المدرسة / المؤسسة التعليمية'),
        ),
        migrations.AlterField(
            model_name='familyinfo',
            name='income_range',
            field=models.CharField(blank=True, choices=[('very_low', 'أقل من 3,000 ريال'), ('low', '3,000 – 6,000 ريال'), ('medium', '6,000 – 10,000 ريال'), ('high', '10,000 – 20,000 ريال'), ('very_high', 'أكثر من 20,000 ريال')], max_length=20, verbose_name='الدخل الشهري التقريبي'),
        ),
        migrations.AlterField(
            model_name='familyinfo',
            name='sibling_order',
            field=models.PositiveIntegerField(verbose_name='ترتيب المستفيد بين الإخوة'),
        ),
        migrations.AlterField(
            model_name='familyinfo',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_info', to='students.student', verbose_name='المستفيد'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student', verbose_name='المستفيد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/%Y/%m/', verbose_name='صورة المستفيد'),
        ),
        migrations.AlterField(
            model_name='studentattachment',
            name='attachment_type',
            field=models.CharField(choices=[('national_id', 'صورة الهوية'), ('birth_certificate', 'شهادة الميلاد'), ('medical_report', 'تقرير طبي'), ('psychological_report', 'تقرير نفسي'), ('disability_card', 'بطاقة إعاقة'), ('referral_letter', 'خطاب إحالة'), ('other', 'أخرى')], max_length=30, verbose_name='نوع المرفق'),
        ),
        migrations.AlterField(
            model_name='studentattachment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='students.student', verbose_name='المستفيد'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['disability_type'], name='students_st_disabil_1c3b63_idx'),
        ),
    ]
