# Generated by Django 4.2.13 on 2026-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_guardian_auth_token'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_disabil_1c3b63_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_first_n_ae97bb_idx',
            old_name='students_st_first_n_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_family__b580a7_idx',
            old_name='students_st_family_n_idx',
        ),
        migrations.AddField(
            model_name='student',
            name='iq_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='درجة الذكاء'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'في انتظار القبول'), ('active', 'نشط'), ('inactive', 'غير نشط'), ('graduated', 'خرّيج'), ('suspended', 'موقوف'), ('transferred', 'محوّل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
