# Generated by Django 4.2.13 on 2026-08-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_iq_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattachment',
            name='attachment_type',
            field=models.CharField(choices=[('national_id', 'صورة الهوية'), ('birth_certificate', 'شهادة الميلاد'), ('family_card', 'كرت العائلة'), ('medical_report', 'تقرير طبي'), ('psychological_report', 'تقرير نفسي'), ('disability_card', 'بطاقة إعاقة'), ('referral_letter', 'خطاب إحالة'), ('other', 'أخرى')], max_length=30, verbose_name='نوع المرفق'),
        ),
    ]
