# Generated by Django 4.2.13 on 2026-08-26 18:58 — hand-edited to add data migration.

from django.db import migrations, models


def convert_to_per_type_degree(apps, schema_editor):
    """Merge the old single disability_degree into each disability_type entry:
    ['autism'] + degree='moderate' -> [{'type': 'autism', 'degree': 'moderate'}].
    If more than one type was selected, the same overall degree is applied to
    all of them (best-effort — matches existing tested data 1:1, no records
    currently have more than one disability_type)."""
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all():
        types = student.disability_type if isinstance(student.disability_type, list) else []
        degree = student.disability_degree or ''
        new_value = [
            {'type': t, 'degree': degree} if isinstance(t, str) else t
            for t in types
        ]
        student.disability_type = new_value
        student.save(update_fields=['disability_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_studentattachment_attachment_type'),
    ]

    operations = [
        migrations.RunPython(convert_to_per_type_degree, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='student',
            name='disability_degree',
        ),
        migrations.AlterField(
            model_name='student',
            name='disability_type',
            field=models.JSONField(default=list, verbose_name='نوع الإعاقة ودرجتها'),
        ),
    ]
