# Generated by Django 4.2.13 on 2026-08-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bus'),
        ('students', '0012_disability_type_per_type_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.bus', verbose_name='الباص'),
        ),
    ]
