# Generated by Django 4.2.13 on 2026-08-26 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0013_student_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', 'الأحد'), ('monday', 'الاثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس')], max_length=10, verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('subject', models.CharField(max_length=100, verbose_name='المادة / الحصة')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to=settings.AUTH_USER_MODEL, verbose_name='الأخصائي المسؤول')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='students.student', verbose_name='المستفيد')),
            ],
            options={
                'verbose_name': 'حصة',
                'verbose_name_plural': 'الجدول الدراسي',
                'ordering': ['day', 'start_time'],
                'unique_together': {('student', 'day', 'start_time')},
            },
        ),
    ]
