# Generated by Django 4.2.13 on 2026-08-26 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0014_studentschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMedicalCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(verbose_name='التاريخ')),
                ('check_time', models.TimeField(blank=True, null=True, verbose_name='وقت الوصول')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_checkins', to=settings.AUTH_USER_MODEL, verbose_name='سُجِّل بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_checkins', to='students.student', verbose_name='المستفيد')),
            ],
            options={
                'verbose_name': 'تشيك إن طبي',
                'verbose_name_plural': 'التشيك إن الطبي',
                'ordering': ['-check_date'],
                'unique_together': {('student', 'check_date')},
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الدواء')),
                ('dose', models.CharField(blank=True, max_length=100, verbose_name='الجرعة')),
                ('frequency', models.CharField(blank=True, max_length=100, verbose_name='عدد المرات باليوم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='students.student', verbose_name='المستفيد')),
            ],
            options={
                'verbose_name': 'دواء',
                'verbose_name_plural': 'الأدوية',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='الطول (سم)')),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='الوزن (كجم)')),
                ('chronic_disease', models.TextField(blank=True, verbose_name='الأمراض المزمنة')),
                ('medical_allergy', models.TextField(blank=True, verbose_name='الحساسية الطبية')),
                ('food_allergy', models.TextField(blank=True, verbose_name='الحساسية الغذائية')),
                ('has_seizures', models.BooleanField(default=False, verbose_name='يعاني من تشنجات')),
                ('uses_nebulizer', models.BooleanField(default=False, verbose_name='يستخدم جهاز الاستنشاق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to='students.student', verbose_name='المستفيد')),
            ],
            options={
                'verbose_name': 'ملف طبي',
                'verbose_name_plural': 'الملفات الطبية',
            },
        ),
        migrations.CreateModel(
            name='MedicalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('status', models.CharField(choices=[('stable', 'مستقر'), ('unstable', 'غير مستقر')], max_length=10, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_visits', to=settings.AUTH_USER_MODEL, verbose_name='قُيِّم بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_visits', to='students.student', verbose_name='المستفيد')),
            ],
            options={
                'verbose_name': 'زيارة تقييم طبي',
                'verbose_name_plural': 'زيارات التقييم الطبي',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given', models.BooleanField(default=False, verbose_name='أُعطي')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_records', to='students.dailymedicalcheckin', verbose_name='التشيك إن')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='students.medication', verbose_name='الدواء')),
            ],
            options={
                'verbose_name': 'إعطاء دواء',
                'verbose_name_plural': 'سجلات إعطاء الأدوية',
                'unique_together': {('checkin', 'medication')},
            },
        ),
    ]
