# Generated by Django 4.2.13 on 2026-08-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_dailymedicalcheckin_medication_studentmedicalprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymedicalcheckin',
            name='blood_pressure_diastolic',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الضغط الانبساطي'),
        ),
        migrations.AddField(
            model_name='dailymedicalcheckin',
            name='blood_pressure_systolic',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الضغط الانقباضي'),
        ),
        migrations.AddField(
            model_name='dailymedicalcheckin',
            name='blood_sugar',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سكر الدم'),
        ),
        migrations.AddField(
            model_name='dailymedicalcheckin',
            name='pulse',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='النبض'),
        ),
        migrations.AddField(
            model_name='dailymedicalcheckin',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='درجة الحرارة'),
        ),
        migrations.AddField(
            model_name='dailymedicalcheckin',
            name='weight_kg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الوزن (كجم)'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='given_at',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الإعطاء'),
        ),
    ]
