# Generated by Django 4.2.13 on 2026-09-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_dailymedicalcheckin_blood_pressure_diastolic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalvisit',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='درجة الحرارة'),
        ),
    ]
