# Generated by Django 4.2.13 on 2026-09-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_medicalvisit_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bus_shift',
            field=models.CharField(blank=True, choices=[('morning', 'صباحي'), ('evening', 'مسائي')], max_length=10, verbose_name='فترة الباص'),
        ),
        migrations.AddField(
            model_name='student',
            name='residence_address',
            field=models.TextField(blank=True, verbose_name='عنوان السكن'),
        ),
    ]
