# Generated by Django 4.2.13 on 2026-10-04 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0019_student_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء الخطة')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء الخطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئت بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='students.student', verbose_name='المستفيد')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_as_teacher', to=settings.AUTH_USER_MODEL, verbose_name='المعلم/ة')),
            ],
            options={
                'verbose_name': 'خطة شهرية',
                'verbose_name_plural': 'الخطط الشهرية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PlanGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('social', 'الاجتماعي'), ('independence', 'الاستقلالي'), ('cognitive', 'المعرفي'), ('communication', 'التواصل'), ('perceptual', 'الإدراكي'), ('motor', 'الحركي')], max_length=20, verbose_name='المجال')),
                ('goals_text', models.TextField(blank=True, verbose_name='الأهداف')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='students.plan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'أهداف مجال',
                'verbose_name_plural': 'أهداف المجالات',
                'ordering': ['plan'],
                'unique_together': {('plan', 'domain')},
            },
        ),
    ]
